import type { Item } from '../../backend';
import type { ShopResult } from '../providers/placesProviders';
import { estimateTotalCost } from '../costing';

interface PDFParams {
  location: string;
  preferredDateTime: Date;
  budget: number;
  items: Item[];
  shop: ShopResult;
  notes: string;
  priceOverrides: Record<string, number>;
}

export async function generatePDF(params: PDFParams): Promise<void> {
  const { location, preferredDateTime, budget, items, shop, notes, priceOverrides } = params;

  const total = estimateTotalCost(items, priceOverrides);

  // Create a simple HTML document for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Shopping Schedule</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
        h1 { color: #333; border-bottom: 2px solid #f97316; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 20px; }
        .info { margin: 10px 0; }
        .label { font-weight: bold; }
        .items { list-style: none; padding: 0; }
        .items li { padding: 5px 0; border-bottom: 1px solid #eee; }
        .total { font-size: 1.5em; font-weight: bold; margin: 20px 0; }
        .budget { color: ${total > budget ? '#dc2626' : '#16a34a'}; }
      </style>
    </head>
    <body>
      <h1>Shopping Schedule</h1>
      
      <h2>Trip Details</h2>
      <div class="info"><span class="label">Location:</span> ${location}</div>
      <div class="info"><span class="label">Date & Time:</span> ${preferredDateTime.toLocaleString('en-IN')}</div>
      <div class="info"><span class="label">Budget:</span> ₹${budget}</div>
      
      <h2>Selected Shop</h2>
      <div class="info"><span class="label">Name:</span> ${shop.name}</div>
      <div class="info"><span class="label">Address:</span> ${shop.address}</div>
      <div class="info"><span class="label">Distance:</span> ${shop.distanceKm.toFixed(1)} km</div>
      ${shop.phone ? `<div class="info"><span class="label">Phone:</span> ${shop.phone}</div>` : ''}
      
      <h2>Shopping Items</h2>
      <ul class="items">
        ${items.map(item => `<li>${item.name}</li>`).join('')}
      </ul>
      
      <div class="total">
        <span class="label">Estimated Total:</span> 
        <span class="budget">₹${total.toFixed(2)}</span>
      </div>
      
      ${notes ? `
        <h2>Notes & Reminders</h2>
        <p>${notes}</p>
      ` : ''}
      
      <p style="margin-top: 40px; color: #888; font-size: 0.9em;">
        Generated by Smart Shopping Planner
      </p>
    </body>
    </html>
  `;

  // Create a new window and print
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    
    // Wait for content to load then print
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}
