/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Item { 'name' : string }
export interface Schedule {
  'id' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'preferredDateTime' : Time,
  'items' : Array<Item>,
  'budget' : bigint,
  'selectedShop' : [] | [Shop],
  'location' : string,
}
export interface Shop { 'name' : string }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'preferredLocation' : [] | [string],
  'defaultBudget' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuickBuyItem' : ActorMethod<[Item], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'comparePrices' : ActorMethod<[Item, Array<Shop>], Array<bigint>>,
  'deleteSchedule' : ActorMethod<[bigint], boolean>,
  'discoverShops' : ActorMethod<[string], Array<Shop>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDemoShops' : ActorMethod<[], Array<Shop>>,
  'getQuickBuyList' : ActorMethod<[], Array<Item>>,
  'getSchedule' : ActorMethod<[bigint], [] | [Schedule]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllSchedules' : ActorMethod<[], Array<Schedule>>,
  'listSchedules' : ActorMethod<[], Array<Schedule>>,
  'removeQuickBuyItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSchedule' : ActorMethod<
    [string, Time, bigint, Array<Item>, [] | [Shop]],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];