/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({ 'name' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Shop = IDL.Record({ 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'preferredLocation' : IDL.Opt(IDL.Text),
  'defaultBudget' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Schedule = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'preferredDateTime' : Time,
  'items' : IDL.Vec(Item),
  'budget' : IDL.Nat,
  'selectedShop' : IDL.Opt(Shop),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuickBuyItem' : IDL.Func([Item], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'comparePrices' : IDL.Func([Item, IDL.Vec(Shop)], [IDL.Vec(IDL.Nat)], []),
  'deleteSchedule' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'discoverShops' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDemoShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getQuickBuyList' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getSchedule' : IDL.Func([IDL.Nat], [IDL.Opt(Schedule)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'listSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
  'removeQuickBuyItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSchedule' : IDL.Func(
      [IDL.Text, Time, IDL.Nat, IDL.Vec(Item), IDL.Opt(Shop)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({ 'name' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Shop = IDL.Record({ 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'preferredLocation' : IDL.Opt(IDL.Text),
    'defaultBudget' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Schedule = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'preferredDateTime' : Time,
    'items' : IDL.Vec(Item),
    'budget' : IDL.Nat,
    'selectedShop' : IDL.Opt(Shop),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuickBuyItem' : IDL.Func([Item], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'comparePrices' : IDL.Func([Item, IDL.Vec(Shop)], [IDL.Vec(IDL.Nat)], []),
    'deleteSchedule' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'discoverShops' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDemoShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getQuickBuyList' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getSchedule' : IDL.Func([IDL.Nat], [IDL.Opt(Schedule)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'listSchedules' : IDL.Func([], [IDL.Vec(Schedule)], ['query']),
    'removeQuickBuyItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSchedule' : IDL.Func(
        [IDL.Text, Time, IDL.Nat, IDL.Vec(Item), IDL.Opt(Shop)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };